import type { Metadata } from 'next'
import { Geist, Geist_Mono, Limelight } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import AuthGuard from '@/features/user/AuthGuard'

export const metadata: Metadata = {
  title: 'Zling',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={`antialiased`}>
        <Providers>
          <AuthGuard>{children}</AuthGuard>
        </Providers>
      </body>
    </html>
  )
}
